services:
  postgres:
    image: postgres:17-alpine
    container_name: demo-app-postgres
    environment:
      POSTGRES_DB: auth-demo-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth-demo-api" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: demo-app
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: auth-demo-api
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: "change-this-secret-to-at-least-32-characters"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
      DEBUG: "false"
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
