services:
  auth-postgres:
    image: postgres:17-alpine
    container_name: auth-service-postgres
    environment:
      POSTGRES_DB: auth-demo-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d auth-demo-api" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data

  user-postgres:
    image: postgres:17-alpine
    container_name: user-service-postgres
    environment:
      POSTGRES_DB: user-demo-api
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d user-demo-api" ]
      interval: 5s
      timeout: 5s
      retries: 20
    volumes:
      - user_postgres_data:/var/lib/postgresql/data

  user-service:
    build:
      context: .
      dockerfile: services/user-service/Dockerfile
    container_name: user-service
    environment:
      DB_HOST: user-postgres
      DB_PORT: 5432
      DB_NAME: user-demo-api
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: "change-this-secret-to-at-least-32-characters"
      INTERNAL_API_KEY: "internal-dev-key"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
      DEBUG: "false"
    ports:
      - "8081:8081"
    depends_on:
      user-postgres:
        condition: service_healthy

  auth-service:
    build:
      context: .
      dockerfile: services/auth-service/Dockerfile
    container_name: auth-service
    environment:
      DB_HOST: auth-postgres
      DB_PORT: 5432
      DB_NAME: auth-demo-api
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
      JWT_SECRET: "change-this-secret-to-at-least-32-characters"
      USER_SERVICE_BASE_URL: "http://user-service:8081"
      USER_SERVICE_INTERNAL_API_KEY: "internal-dev-key"
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_FLYWAY_ENABLED: true
      DEBUG: "false"
    ports:
      - "8080:8080"
    depends_on:
      auth-postgres:
        condition: service_healthy
      user-service:
        condition: service_started

volumes:
  auth_postgres_data:
  user_postgres_data:
